/* Generated by Phoenix Tuner X */
package frc.robot;

import static edu.wpi.first.units.Units.*;

import edu.wpi.first.wpilibj.util.Color;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.FireAnimation;
import com.ctre.phoenix6.controls.SolidColor;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.RGBWColor;

/**
 * Subsystem that controls an addressable LED strip using a CANdle.
 */
public class LEDSubsystem extends SubsystemBase {
    private final CANBus kCANBus = new CANBus("subsystems");
    private final CANdle m_candle = new CANdle(55, kCANBus);

    private final FireAnimation m_slot0Animation = new FireAnimation(60, 0)
        .withSlot(0)
        .withBrightness(1)
        .withDirection(AnimationDirectionValue.Forward)
        .withSparking(1)
        .withCooling(0.3)
        .withFrameRate(Hertz.of(50));

    private final SolidColor[] m_colors = new SolidColor[] {
        // new SolidColor(60, 0).withColor(new RGBWColor(Color.kBlack)),
        new SolidColor(0, 60).withColor(new RGBWColor(Color.kBlack)).withUpdateFreqHz(50)
    };

    public LEDSubsystem() {
        setDefaultCommand(updateLEDs());
    }

    /**
     * Updates the animations and LEDs of the CANdle.
     *
     * @return Command to run
     */
    public Command updateLEDs() {
        return run(() -> {
            for (var solidColor : m_colors) {
                m_candle.setControl(solidColor);
            }
        });
    }
}
